name: Firebase CD
on:
  workflow_dispatch:
  push:
    paths:
      - 'public/**'
      - '.firebaserc'
      - 'firebase.json'
      - '.github/workflows/firebase.yml'
    branches:
      - main

jobs:
  deploy:
    name: Firebase Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
